import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';

const EWayBillTemplate = React.forwardRef(({ data }, ref) => {
  const {
    ewayBillNo,
    documentNo,
    ewayBillDate,
    validFrom,
    validUntil,
    generatedBy,
    supplierGstin,
    recipientGstin,
    placeOfDelivery,
    placeOfDispatch,
    valueOfGoods,
    transportReason,
    transporter,
    vehicles
  } = data;

  // Format dates for display
  const formatDate = (dateString) => {
    if (!dateString) return "-";
    try {
      // Handle both ISO strings and date objects
      const date = typeof dateString === 'string' && dateString.includes('T') 
        ? new Date(dateString).toLocaleString()
        : dateString;
      return date;
    } catch (e) {
      return dateString || "-";
    }
  };

  return (
    <View ref={ref} style={styles.container}>
      <View style={styles.headerContainer}>
        <Text style={styles.title}>E-Way Bill</Text>
      </View>

      <View style={styles.infoSection}>
        <View style={styles.infoColumn}>
          <Text style={styles.infoRow}><Text style={styles.bold}>E-way Bill No:</Text> {ewayBillNo || '-'}</Text>
          <Text style={styles.infoRow}><Text style={styles.bold}>Document No:</Text> {documentNo || '-'}</Text>
          <Text style={styles.infoRow}><Text style={styles.bold}>Date:</Text> {ewayBillDate || '-'}</Text>
        </View>
        <View style={styles.infoColumn}>
          <Text style={styles.infoRow}><Text style={styles.bold}>Valid From:</Text> {formatDate(validFrom)}</Text>
          <Text style={styles.infoRow}><Text style={styles.bold}>Valid Until:</Text> {formatDate(validUntil)}</Text>
          <Text style={styles.infoRow}><Text style={styles.bold}>Generated By:</Text> {generatedBy || '-'}</Text>
        </View>
      </View>

      <View style={styles.sectionContainer}>
        <Text style={styles.sectionTitle}>Part A - Basic Details</Text>
        <View style={styles.detailsGrid}>
          <Text style={styles.detailItem}><Text style={styles.bold}>GSTIN of Supplier:</Text> {supplierGstin || '-'}</Text>
          <Text style={styles.detailItem}><Text style={styles.bold}>GSTIN of Recipient:</Text> {recipientGstin || '-'}</Text>
          <Text style={styles.detailItem}><Text style={styles.bold}>Place of Delivery:</Text> {placeOfDelivery || '-'}</Text>
          <Text style={styles.detailItem}><Text style={styles.bold}>Place of Dispatch:</Text> {placeOfDispatch || '-'}</Text>
          <Text style={styles.detailItem}><Text style={styles.bold}>Value of Goods:</Text> ₹{valueOfGoods || '0'}</Text>
          <Text style={styles.detailItem}><Text style={styles.bold}>Reason:</Text> {transportReason || '-'}</Text>
          <Text style={styles.detailItem}><Text style={styles.bold}>Transporter:</Text> {transporter || '-'}</Text>
        </View>
      </View>

      <View style={styles.sectionContainer}>
        <Text style={styles.sectionTitle}>Part B - Vehicle Details</Text>
        <ScrollView horizontal={true}>
          <View style={styles.tableContainer}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableHeaderCell, { width: 100 }]}>Mode</Text>
              <Text style={[styles.tableHeaderCell, { width: 120 }]}>Vehicle No</Text>
              <Text style={[styles.tableHeaderCell, { width: 150 }]}>From</Text>
              <Text style={[styles.tableHeaderCell, { width: 180 }]}>Entered Date</Text>
              <Text style={[styles.tableHeaderCell, { width: 150 }]}>Entered By</Text>
            </View>
            {vehicles && vehicles.map((vehicle, index) => (
              <View key={index} style={styles.tableRow}>
                <Text style={[styles.tableCell, { width: 100 }]}>{vehicle.mode || '-'}</Text>
                <Text style={[styles.tableCell, { width: 120 }]}>{vehicle.vehicleNo || '-'}</Text>
                <Text style={[styles.tableCell, { width: 150 }]}>{vehicle.from || '-'}</Text>
                <Text style={[styles.tableCell, { width: 180 }]}>{formatDate(vehicle.enteredDate)}</Text>
                <Text style={[styles.tableCell, { width: 150 }]}>{vehicle.enteredBy || '-'}</Text>
              </View>
            ))}
          </View>
        </ScrollView>
      </View>

      <View style={styles.footer}>
        <Text style={styles.footerText}>Note: This is an electronically generated document.</Text>
      </View>
    </View>
  );
});

const styles = StyleSheet.create({
  container: {
    padding: 16,
    backgroundColor: 'white',
    marginBottom: 20,
  },
  headerContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
  },
  infoSection: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  infoColumn: {
    flex: 1,
  },
  infoRow: {
    fontSize: 14,
    marginBottom: 6,
  },
  bold: {
    fontWeight: 'bold',
  },
  sectionContainer: {
    marginBottom: 20,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#ddd',
    paddingVertical: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  detailItem: {
    width: '50%',
    paddingVertical: 4,
    fontSize: 14,
  },
  tableContainer: {
    borderWidth: 1,
    borderColor: '#ddd',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f0f0f0',
    paddingVertical: 8,
  },
  tableHeaderCell: {
    fontWeight: 'bold',
    padding: 8,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#ddd',
    fontSize: 14,
  },
  tableRow: {
    flexDirection: 'row',
  },
  tableCell: {
    padding: 8,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#ddd',
    fontSize: 14,
  },
  footer: {
    marginTop: 20,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
  }
});

export default EWayBillTemplate;