import React from "react";

const EwayTemplate = React.forwardRef(({ data }, ref) => {
  const {
    ewayBillNo,
    documentNo,
    ewayBillDate,
    validFrom,
    validUntil,
    generatedBy,
    supplierGstin,
    recipientGstin,
    placeOfDelivery,
    placeOfDispatch,
    valueOfGoods,
    transportReason,
    transporter,
    vehicles
  } = data;

  return (
    <div
      ref={ref}
      className="w-[210mm] mx-auto p-6 font-sans border border-gray-700"
      style={{ minHeight: "297mm" }}
    >
      <div className="text-center mb-6">
        <h1 className="text-2xl font-bold">E-Way Bill</h1>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-6">
        <div>
          <p><strong>E-way Bill No:</strong> {ewayBillNo}</p>
          <p><strong>Document No:</strong> {documentNo}</p>
          <p><strong>Date:</strong> {ewayBillDate}</p>
        </div>
        <div>
          <p><strong>Valid From:</strong> {validFrom}</p>
          <p><strong>Valid Until:</strong> {validUntil}</p>
          <p><strong>Generated By:</strong> {generatedBy}</p>
        </div>
      </div>

      <div className="border-t border-b border-gray-300 py-4 mb-6">
        <h2 className="text-xl font-bold mb-4">Part A - Basic Details</h2>
        <div className="grid grid-cols-2 gap-4">
          <p><strong>GSTIN of Supplier:</strong> {supplierGstin}</p>
          <p><strong>GSTIN of Recipient:</strong> {recipientGstin}</p>
          <p><strong>Place of Delivery:</strong> {placeOfDelivery}</p>
          <p><strong>Place of Dispatch:</strong> {placeOfDispatch}</p>
          <p><strong>Value of Goods:</strong> ₹{valueOfGoods}</p>
          <p><strong>Reason:</strong> {transportReason}</p>
          <p><strong>Transporter:</strong> {transporter}</p>
        </div>
      </div>

      <div>
        <h2 className="text-xl font-bold mb-4">Part B - Vehicle Details</h2>
        <table className="w-full border-collapse">
          <thead>
            <tr className="bg-gray-100">
              <th className="border p-2">Mode</th>
              <th className="border p-2">Vehicle No</th>
              <th className="border p-2">From</th>
              <th className="border p-2">Entered Date</th>
              <th className="border p-2">Entered By</th>
            </tr>
          </thead>
          <tbody>
            {vehicles.map((vehicle, index) => (
              <tr key={index}>
                <td className="border p-2">{vehicle.mode}</td>
                <td className="border p-2">{vehicle.vehicleNo}</td>
                <td className="border p-2">{vehicle.from}</td>
                <td className="border p-2">{vehicle.enteredDate}</td>
                <td className="border p-2">{vehicle.enteredBy}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-6 text-sm text-gray-600">
        <p>Note: This is an electronically generated document.</p>
      </div>
    </div>
  );
});

export default EwayTemplate;