import React from "react";

export default function EwayForm({ formData, setFormData, onGenerate }) {
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleValidFromChange = (e) => {
    const validFrom = e.target.value;
    if (validFrom) {
      const validFromDate = new Date(validFrom);
      const validUntilDate = new Date(validFromDate);
      validUntilDate.setMonth(validUntilDate.getMonth() + 3);
      setFormData(prev => ({
        ...prev,
        validFrom,
        validUntil: validUntilDate.toISOString().slice(0, 16)
      }));
    }
  };

  const handleAddVehicle = () => {
    setFormData(prev => ({
      ...prev,
      vehicles: [...prev.vehicles, {
        mode: "Road",
        vehicleNo: "",
        from: "",
        enteredDate: "",
        enteredBy: ""
      }]
    }));
  };

  const handleRemoveVehicle = (index) => {
    setFormData(prev => ({
      ...prev,
      vehicles: prev.vehicles.filter((_, idx) => idx !== index)
    }));
  };

  const handleVehicleChange = (index, field, value) => {
    setFormData(prev => {
      const newVehicles = [...prev.vehicles];
      newVehicles[index] = {
        ...newVehicles[index],
        [field]: value
      };
      return {
        ...prev,
        vehicles: newVehicles
      };
    });
  };

  return (
    <div className="space-y-4">
      {/* Part A */}
      <div className="border p-4 rounded">
        <h3 className="font-bold mb-4">Part A - Basic Details</h3>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block font-semibold">Generated By:</label>
            <input
              type="text"
              name="generatedBy"
              value={formData.generatedBy}
              onChange={handleInputChange}
              className="border rounded p-1 w-full"
            />
          </div>
          <div>
            <label className="block font-semibold">Valid From:</label>
            <input
              type="datetime-local"
              name="validFrom"
              value={formData.validFrom}
              onChange={handleValidFromChange}
              className="border rounded p-1 w-full"
            />
          </div>
          <div>
            <label className="block font-semibold">Valid Until:</label>
            <input
              type="datetime-local"
              name="validUntil"
              value={formData.validUntil}
              onChange={handleInputChange}
              className="border rounded p-1 w-full"
            />
          </div>
          <div>
            <label className="block font-semibold">GSTIN of Supplier:</label>
            <input
              type="text"
              name="supplierGstin"
              value={formData.supplierGstin}
              onChange={handleInputChange}
              className="border rounded p-1 w-full"
            />
          </div>
          <div>
            <label className="block font-semibold">GSTIN of Recipient:</label>
            <input
              type="text"
              name="recipientGstin"
              value={formData.recipientGstin}
              onChange={handleInputChange}
              className="border rounded p-1 w-full"
            />
          </div>
          <div>
            <label className="block font-semibold">Place of Delivery:</label>
            <input
              type="text"
              name="placeOfDelivery"
              value={formData.placeOfDelivery}
              onChange={handleInputChange}
              className="border rounded p-1 w-full"
            />
          </div>
          <div>
            <label className="block font-semibold">Place of Dispatch:</label>
            <input
              type="text"
              name="placeOfDispatch"
              value={formData.placeOfDispatch}
              onChange={handleInputChange}
              className="border rounded p-1 w-full"
            />
          </div>
          <div>
            <label className="block font-semibold">Value of Goods:</label>
            <input
              type="number"
              name="valueOfGoods"
              value={formData.valueOfGoods}
              onChange={handleInputChange}
              className="border rounded p-1 w-full"
            />
          </div>
          <div>
            <label className="block font-semibold">Reason for Transportation:</label>
            <select
              name="transportReason"
              value={formData.transportReason}
              onChange={handleInputChange}
              className="border rounded p-1 w-full"
            >
              <option value="Supply">Supply</option>
              <option value="Export">Export</option>
              <option value="Job Work">Job Work</option>
              <option value="Others">Others</option>
            </select>
          </div>
          <div>
            <label className="block font-semibold">Transporter:</label>
            <input
              type="text"
              name="transporter"
              value={formData.transporter}
              onChange={handleInputChange}
              className="border rounded p-1 w-full"
            />
          </div>
        </div>
      </div>

      {/* Part B */}
      <div className="border p-4 rounded">
        <div className="flex justify-between items-center mb-4">
          <h3 className="font-bold">Part B - Vehicle Details</h3>
          <button
            type="button"
            onClick={handleAddVehicle}
            className="bg-green-500 text-white px-4 py-2 rounded"
          >
            Add Vehicle
          </button>
        </div>

        {formData.vehicles.map((vehicle, idx) => (
          <div key={idx} className="border p-4 rounded mb-4">
            <div className="flex justify-between items-center mb-4">
              <h4 className="font-semibold">Vehicle #{idx + 1}</h4>
              {formData.vehicles.length > 1 && (
                <button
                  type="button"
                  onClick={() => handleRemoveVehicle(idx)}
                  className="text-red-500"
                >
                  Remove
                </button>
              )}
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block font-semibold">Mode:</label>
                <select
                  value={vehicle.mode}
                  onChange={(e) => handleVehicleChange(idx, 'mode', e.target.value)}
                  className="border rounded p-1 w-full"
                >
                  <option value="Road">Road</option>
                  <option value="Rail">Rail</option>
                  <option value="Air">Air</option>
                  <option value="Ship">Ship</option>
                </select>
              </div>
              <div>
                <label className="block font-semibold">Vehicle No:</label>
                <input
                  type="text"
                  value={vehicle.vehicleNo}
                  onChange={(e) => handleVehicleChange(idx, 'vehicleNo', e.target.value)}
                  className="border rounded p-1 w-full"
                />
              </div>
              <div>
                <label className="block font-semibold">From:</label>
                <input
                  type="text"
                  value={vehicle.from}
                  onChange={(e) => handleVehicleChange(idx, 'from', e.target.value)}
                  className="border rounded p-1 w-full"
                />
              </div>
              <div>
                <label className="block font-semibold">Entered Date:</label>
                <input
                  type="datetime-local"
                  value={vehicle.enteredDate}
                  onChange={(e) => handleVehicleChange(idx, 'enteredDate', e.target.value)}
                  className="border rounded p-1 w-full"
                />
              </div>
              <div>
                <label className="block font-semibold">Entered By:</label>
                <input
                  type="text"
                  value={vehicle.enteredBy}
                  onChange={(e) => handleVehicleChange(idx, 'enteredBy', e.target.value)}
                  className="border rounded p-1 w-full"
                />
              </div>
            </div>
          </div>
        ))}
      </div>

      <button
        type="button"
        onClick={onGenerate}
        className="bg-blue-600 text-white px-6 py-2 rounded shadow w-full"
      >
        Generate E-way Bill
      </button>
    </div>
  );
}